apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beerlog
  name: beerlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerlog
  strategy: {}
  template:
    metadata:
      labels:
        app: beerlog
    spec:
      containers:
      - image: umluizlima/beerlog:latest
        name: beerlog
        ports:
        - containerPort: 8000
        resources: {}
status: {}
